language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hiddencompass' ]; then cd .. && eval "mv $currentfolder generator-hiddencompass" && cd generator-hiddencompass; fi
